name: ci

on:
  push:
    paths-ignore:
      - ".github"
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  main:
    concurrency: "build"
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: islishude
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: islishude/web3-cli
      - name: Build and push
        uses: docker/build-push-action@v3
        timeout-minutes: 10
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
