name: ci

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: islishude
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: islishude/web3-cli:latest
      - name: Build and push
        id: docker_build_with_tag
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: islishude/web3-cli:latest,islishude/web3-cli:${{ github.ref_name }}
